### ISSUE TITLE
Some problems with google API ?

### ISSUE THREAD

**Issue by aymeric59** [Tobi042/cafe-bot-cobot#1] opened 2021-02-18 17:21 UTC
Hi !

I use Cobot for my coworking space in France.

Your app is so great, I put it on ly Cobot account, all is going quite well but it's not possible to retrieve data from the google sheets doc. 
It seems this the API now works differently. 

Do you think you could fix it or give some help to solve this issue ?

Regards

Aymeric.

**Comment by tobias-theobald** [comment] 2021-06-16 15:34
Hi, we've been able to finally reproduce the issue. The problem was that the wrong Google API to use in your project was noted in the instructions. They said Google Docs API, where it should've been Google Sheets API. 

Sorry for the confusion, the instructions are fixed now

**Closed as completed by tobias-theobald** 2021-06-16 15:34 UTC
